### ISSUE TITLE
run env HumanoidStandup-v1 error

### ISSUE THREAD

**Issue by zdx3578** [songrotek/DDPG#1]
in Humanoid-v1 env; also error this when run some  time,if STEPS smaller , the error appear is later

[2016-05-28 10:53:54,309] Starting new video recorder writing to /Users/lmj/Documents/t/ddpgout/1/HumanoidStandup-v1-DDPG-5/openaigym.video.None.2001.video000000.mp4
[2016-05-28 10:53:59,759] Finished writing results. You can upload them to the scoreboard via gym.upload('/Users/lmj/Documents/t/ddpgout/1/HumanoidStandup-v1-DDPG-5')
Traceback (most recent call last):
  File "gym_ddpg.py", line 43, in <module>
    main()
  File "gym_ddpg.py", line 33, in main
    agent.set_feedback(observation,action,reward,done)
  File "/Users/lmj/develop/DDPG/ddpg.py", line 98, in set_feedback
    self.train()
  File "/Users/lmj/develop/DDPG/ddpg.py", line 66, in train
    self.critic_network.train(y_batch,state_batch,action_batch)
  File "/Users/lmj/develop/DDPG/critic_network.py", line 93, in train
    self.action_input:action_batch
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 553, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 64, 1) for Tensor u'Placeholder_4:0', which has shape '(?, 1)'

**Comment by floodsung** [comment]
had totally reimplemented.
