### ISSUE TITLE
Error: No module named utlility

### ISSUE THREAD

**Issue by truell20** [songrotek/DDPG#3]
Using python2.7 on ubuntu 14.04:

```bash
Traceback (most recent call last):
  File "gym_ddpg.py", line 2, in <module>
    from ddpg import *
  File "/home/truell20/Documents/ddpg-aigym/DDPG/ddpg.py", line 10, in <module>
    from critic_network import CriticNetwork 
  File "/home/truell20/Documents/ddpg-aigym/DDPG/critic_network.py", line 3, in <module>
    from utility import *
ImportError: No module named utility
```

**Comment by ethanfetaya** [comment]
Have the same issue

**Comment by songrotek** [comment]
had fixed the bug.
