### ISSUE TITLE
AttributeError: 'FilteredEnv' object has no attribute 'monitor'

### ISSUE THREAD

**Issue by inksci** [songrotek/DDPG#9]
```
Traceback (most recent call last):
  File "gym_ddpg.py", line 43, in <module>
    main()
  File "gym_ddpg.py", line 13, in main
    env.monitor.start('experiments/' + ENV_NAME,force=True)
AttributeError: 'FilteredEnv' object has no attribute 'monitor'
```
```
>>> tf.__version__
'1.3.0'
>>> import gym
>>> gym.__version__
'0.9.3'
```

**Comment by inksci** [comment]
I just comment out the related code:
```
# env.monitor.start('experiments/' + ENV_NAME,force=True)
```
It works!

**Comment by MahtabSarvmaili** [comment]
Hi 
I had the same problem.
Is there any way to solve this problem without commenting any line of code?
